development:
  adapter: postgresql
  database: gradecraft_development
  min_messages: warning
  pool: 16

test:
  adapter: postgresql
  database: gradecraft_test
  encoding: unicode
  min_messages: warning
  pool: 16

# for staging and production use DATABASE_URL, see: http://edgeguides.rubyonrails.org/configuring.html#configuring-a-database
